import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./dashboard/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Editor Json",
  description: "Generated by María-Fernanda Villalobos",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
